// <auto-generated />
using APIpeliculas.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIpeliculas.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250703032300_AgregandoSeeder")]
    partial class AgregandoSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIpeliculas.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Nombre = "Accion"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Aventura"
                        },
                        new
                        {
                            Id = 30,
                            Nombre = "Comedia"
                        },
                        new
                        {
                            Id = 40,
                            Nombre = "Drama"
                        },
                        new
                        {
                            Id = 50,
                            Nombre = "Fantasia"
                        },
                        new
                        {
                            Id = 60,
                            Nombre = "Ciencia Ficcion"
                        },
                        new
                        {
                            Id = 70,
                            Nombre = "Terror"
                        },
                        new
                        {
                            Id = 80,
                            Nombre = "Romance"
                        });
                });

            modelBuilder.Entity("APIpeliculas.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<int>("Estreno")
                        .HasColumnType("int");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.HasIndex("Titulo")
                        .IsUnique();

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "En un futuro postapocalíptico, Max se une a una misteriosa mujer para huir de un tirano.",
                            Director = "George Miller",
                            Duracion = 120,
                            Estreno = 2015,
                            GeneroId = 10,
                            Rating = 0.0,
                            Titulo = "Mad Max: Fury Road"
                        },
                        new
                        {
                            Id = 2,
                            Description = "El arqueólogo Indiana Jones busca el Arca de la Alianza antes que los nazis.",
                            Director = "Steven Spielberg",
                            Duracion = 130,
                            Estreno = 1981,
                            GeneroId = 20,
                            Rating = 8.4000000000000004,
                            Titulo = "Indiana Jones y los cazadores del arca perdida"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dos amigos intentan disfrutar su última fiesta antes de graduarse.",
                            Director = "Greg Mottola",
                            Duracion = 100,
                            Estreno = 2007,
                            GeneroId = 30,
                            Rating = 7.5999999999999996,
                            Titulo = "Superbad"
                        },
                        new
                        {
                            Id = 4,
                            Description = "La historia de la familia mafiosa Corleone.",
                            Director = "Francis Ford Coppola",
                            Duracion = 180,
                            Estreno = 1972,
                            GeneroId = 40,
                            Rating = 9.1999999999999993,
                            Titulo = "El Padrino"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Un hobbit debe destruir un anillo para salvar la Tierra Media.",
                            Director = "Peter Jackson",
                            Duracion = 187,
                            Estreno = 2001,
                            GeneroId = 50,
                            Rating = 8.8000000000000007,
                            Titulo = "El Señor de los Anillos: La Comunidad del Anillo"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Un grupo de astronautas viaja a través de un agujero de gusano en busca de un nuevo hogar para la humanidad.",
                            Director = "Christopher Nolan",
                            Duracion = 180,
                            Estreno = 2014,
                            GeneroId = 60,
                            Rating = 8.5999999999999996,
                            Titulo = "Interestelar"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Investigadores paranormales ayudan a una familia aterrorizada por una presencia oscura.",
                            Director = "James Wan",
                            Duracion = 120,
                            Estreno = 2013,
                            GeneroId = 70,
                            Rating = 7.5,
                            Titulo = "El Conjuro"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Una historia de amor a bordo del trágico Titanic.",
                            Director = "James Cameron",
                            Duracion = 160,
                            Estreno = 1997,
                            GeneroId = 80,
                            Rating = 7.7999999999999998,
                            Titulo = "Titanic"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Un grupo de inadaptados se une para salvar la galaxia.",
                            Director = "James Gunn",
                            Duracion = 140,
                            Estreno = 2014,
                            GeneroId = 10,
                            Rating = 8.0,
                            Titulo = "Guardianes de la Galaxia"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Un pianista y una actriz persiguen sus sueños en Los Ángeles.",
                            Director = "Damien Chazelle",
                            Duracion = 120,
                            Estreno = 2016,
                            GeneroId = 40,
                            Rating = 8.0,
                            Titulo = "La La Land"
                        });
                });

            modelBuilder.Entity("APIpeliculas.Models.Movie", b =>
                {
                    b.HasOne("APIpeliculas.Models.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });
#pragma warning restore 612, 618
        }
    }
}
